[package]
name = "task-manager-rs"
version = "0.1.0"
authors = ["doberan <doberankei@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sedregex = "0.2.4"